import PDFDocument from 'pdfkit';
import type { DRP } from '../drp/types.js';

// Generates a "Brand Guidelines" PDF straight from a DRP — no headless
// browser involved (pdfkit draws vectors/text directly), so this works
// anywhere Node runs: a Vercel serverless function, the CLI, a GitHub
// Actions job. It also means it needs neither the Claude API nor Vercel
// Blob, since it only reads a DRP already sitting in the database and
// streams the finished bytes straight back — nothing to store.
//
// Caveat worth knowing: fonts are rendered in a close PDF-safe stand-in
// (Helvetica/Times/Courier), not the actual detected typeface — pdfkit can
// only render fonts it has the real font file for, and we don't download/
// license the source's actual font files. The name and every measurement
// (size, scale ratio, spacing, radii) is exact; the *shape* of the letters
// in the specimen is an approximation.

const PAGE_MARGIN = 50;
const PAGE_WIDTH = 595.28; // A4 pt
const CONTENT_WIDTH = PAGE_WIDTH - PAGE_MARGIN * 2;

export interface BrandGuideOptions {
  screenshotPng?: Buffer;
}

export async function renderBrandGuidePdf(drp: DRP, opts: BrandGuideOptions = {}): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: PAGE_MARGIN, bufferPages: true });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    drawCoverPage(doc, drp, opts.screenshotPng);
    drawColorPage(doc, drp);
    drawTypographyPage(doc, drp);
    drawSpacingShapePage(doc, drp);
    drawMotionLayoutPage(doc, drp);
    drawComponentsPage(doc, drp);
    drawProvenancePage(doc, drp);

    addPageFooters(doc, drp);

    doc.end();
  });
}

function sectionHeading(doc: PDFKit.PDFDocument, text: string) {
  doc.fontSize(11).font('Helvetica-Bold').fillColor('#666666').text(text.toUpperCase(), { characterSpacing: 1 });
  doc.moveDown(0.4);
  doc.fillColor('#000000');
}

function drawCoverPage(doc: PDFKit.PDFDocument, drp: DRP, screenshotPng?: Buffer) {
  doc.rect(0, 0, PAGE_WIDTH, 260).fill(drp.color.palette.primary.ramp['700'] ?? drp.color.palette.primary.base);

  doc.fillColor('#FFFFFF').fontSize(11).font('Helvetica').text('BRAND GUIDELINES', PAGE_MARGIN, 60, { characterSpacing: 2 });
  doc.fontSize(30).font('Helvetica-Bold').text(drp.identity.name, PAGE_MARGIN, 85, { width: CONTENT_WIDTH });
  doc.fontSize(12).font('Helvetica').fillColor('#F0F0F0').text(drp.identity.character, PAGE_MARGIN, 150, { width: CONTENT_WIDTH });

  const chips = [drp.identity.theme_mode, drp.identity.density, ...drp.identity.descriptors].slice(0, 8);
  let cx = PAGE_MARGIN;
  let cy = 200;
  doc.fontSize(9).font('Helvetica');
  for (const chip of chips) {
    const w = doc.widthOfString(chip) + 16;
    if (cx + w > PAGE_WIDTH - PAGE_MARGIN) {
      cx = PAGE_MARGIN;
      cy += 22;
    }
    doc.roundedRect(cx, cy, w, 18, 9).fillOpacity(0.18).fill('#FFFFFF').fillOpacity(1);
    doc.fillColor('#FFFFFF').text(chip, cx + 8, cy + 5);
    cx += w + 6;
  }

  doc.fillColor('#000000');

  if (screenshotPng) {
    try {
      doc.image(screenshotPng, PAGE_MARGIN, 290, { fit: [CONTENT_WIDTH, 300], align: 'center' });
    } catch {
      // Not every stored asset is a decodable image (e.g. a stray non-PNG
      // buffer) — a missing screenshot on the cover isn't worth failing the
      // whole document for.
    }
  }

  doc.fontSize(9).fillColor('#888888').text(
    `Generated by StyleSync from ${drp.provenance.source} · ${new Date(drp.provenance.captured_at).toLocaleDateString()}`,
    PAGE_MARGIN,
    doc.page.height - 70,
    { width: CONTENT_WIDTH }
  );
}

function drawColorPage(doc: PDFKit.PDFDocument, drp: DRP) {
  doc.addPage();
  sectionHeading(doc, 'Colour palette');

  const rampSteps = ['50', '100', '200', '300', '400', '500', '600', '700', '800', '900', '950'];
  const swatchW = CONTENT_WIDTH / rampSteps.length;

  for (const [role, ramp] of Object.entries(drp.color.palette)) {
    if (!ramp) continue;
    doc.fontSize(10).font('Helvetica-Bold').fillColor('#000000').text(role, { continued: false });
    const y = doc.y;
    rampSteps.forEach((step, i) => {
      const hex = ramp.ramp[step];
      if (!hex) return;
      const x = PAGE_MARGIN + i * swatchW;
      doc.rect(x, y, swatchW, 28).fill(hex);
      doc.fontSize(6).fillColor(contrastTextColor(hex)).text(step, x + 2, y + 10, { width: swatchW - 4 });
    });
    doc.y = y + 34;
    doc.fillColor('#000000');
  }

  doc.moveDown(1);
  sectionHeading(doc, 'Semantic tokens');
  const semanticEntries = Object.entries(drp.color.semantic);
  const colWidth = CONTENT_WIDTH / 2;
  semanticEntries.forEach(([token, hex], i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const x = PAGE_MARGIN + col * colWidth;
    const y = doc.y + row * 22;
    doc.rect(x, y, 16, 16).fill(hex).stroke('#DDDDDD');
    doc.fontSize(9).font('Helvetica').fillColor('#000000').text(`${token}  ${hex}`, x + 22, y + 3);
  });
  doc.y += Math.ceil(semanticEntries.length / 2) * 22 + 10;

  doc.fontSize(9).fillColor('#666666').text(
    `Min body contrast ${drp.color.contrast_report.min_body_ratio}:1 — WCAG AA ${drp.color.contrast_report.wcag_aa_pass ? 'pass' : 'fail'}` +
      (drp.color.contrast_report.contrast_adjusted ? ' (auto-corrected)' : '')
  );
}

function drawTypographyPage(doc: PDFKit.PDFDocument, drp: DRP) {
  doc.addPage();
  sectionHeading(doc, 'Typography');

  const families = [
    { role: 'Display', font: drp.typography.families.display },
    { role: 'Body', font: drp.typography.families.body },
    { role: 'Mono', font: drp.typography.families.mono },
    ...(drp.typography.families.additional ?? []).map((f) => ({ role: f.role, font: f })),
  ];
  for (const { role, font } of families) {
    doc.fontSize(10).font('Helvetica-Bold').fillColor('#000000').text(`${role}:  `, { continued: true });
    doc.font('Helvetica').fillColor('#444444').text(`${font.stack}  (${font.source})`);
    doc.moveDown(0.3);
  }

  doc.moveDown(0.5);
  doc.fontSize(8).fillColor('#999999').text(
    'Specimens below are set in a PDF-safe stand-in typeface at the real detected size/weight/spacing — the exact letterform of the source font is not embedded.'
  );
  doc.moveDown(0.8);
  doc.fillColor('#000000');

  sectionHeading(doc, `Type scale — ratio ${drp.typography.scale.ratio}, base ${drp.typography.scale.base_px}px`);
  const order = ['2xl', 'xl', 'lg', 'base', 'sm', 'xs'];
  for (const step of order) {
    const t = drp.typography.scale.steps[step];
    if (!t) continue;
    const px = remToPx(t.size);
    doc.font(t.weight >= 600 ? 'Helvetica-Bold' : 'Helvetica').fontSize(Math.min(px, 40)).fillColor('#000000');
    doc.text('The quick brown fox', { continued: false });
    doc.fontSize(8).font('Helvetica').fillColor('#999999').text(`${step} · ${t.size} · weight ${t.weight} · line ${t.line}`);
    doc.moveDown(0.4);
  }
}

function drawSpacingShapePage(doc: PDFKit.PDFDocument, drp: DRP) {
  doc.addPage();
  sectionHeading(doc, `Spacing — ${drp.space.unit_px}px unit`);
  let x = PAGE_MARGIN;
  const y = doc.y;
  for (const px of drp.space.scale) {
    const w = Math.max(2, px);
    doc.rect(x, y, w, 16).fill('#4C6FFF');
    doc.fontSize(7).fillColor('#666666').text(String(px), x, y + 20, { width: Math.max(w, 16) });
    x += w + 8;
    if (x > PAGE_WIDTH - PAGE_MARGIN - 20) {
      x = PAGE_MARGIN;
      doc.y += 40;
    }
  }
  doc.y = Math.max(doc.y, y + 45);
  doc.fillColor('#000000');

  doc.moveDown(1.2);
  sectionHeading(doc, 'Radii');
  let rx = PAGE_MARGIN;
  const ry = doc.y;
  for (const [name, value] of Object.entries(drp.shape.radius)) {
    const size = 48;
    const radiusPx = value.endsWith('px') ? parseFloat(value) : value === '9999px' ? size / 2 : 0;
    doc.roundedRect(rx, ry, size, size, Math.min(radiusPx, size / 2)).fillOpacity(0).lineWidth(1.5).stroke('#4C6FFF');
    doc.fontSize(8).fillColor('#666666').fillOpacity(1).text(`${name}: ${value}`, rx, ry + size + 6, { width: size + 20 });
    rx += size + 30;
  }
  doc.y = ry + 80;

  doc.moveDown(0.5);
  sectionHeading(doc, 'Elevation');
  doc.fontSize(10).font('Helvetica').fillColor('#000000').text(`Strategy: ${drp.elevation.strategy}`);
  doc.moveDown(0.3);
  for (const [level, value] of Object.entries(drp.elevation.levels)) {
    doc.fontSize(9).fillColor('#666666').text(`level ${level} — ${value}`);
  }
}

function drawMotionLayoutPage(doc: PDFKit.PDFDocument, drp: DRP) {
  doc.addPage();
  sectionHeading(doc, 'Motion');
  doc.fontSize(10).font('Helvetica').fillColor('#000000').text(
    `Durations — fast ${drp.motion.durations.fast}ms · base ${drp.motion.durations.base}ms · slow ${drp.motion.durations.slow}ms`
  );
  doc.moveDown(0.3);
  doc.fontSize(9).fillColor('#666666').text(`Reduced motion fallback: ${drp.motion.reduced_motion_fallback}`);
  doc.moveDown(0.6);
  for (const sig of drp.motion.signatures) {
    doc.fontSize(9).fillColor('#000000').text(`• ${sig.trigger} → ${sig.target}: ${sig.effect} (${sig.duration}ms${sig.stagger ? `, stagger ${sig.stagger}ms` : ''})`);
  }

  doc.moveDown(1);
  sectionHeading(doc, 'Layout & navigation');
  doc.fontSize(10).font('Helvetica').fillColor('#000000');
  doc.text(`Nav pattern: ${drp.layout.nav_pattern}`);
  doc.text(`Content alignment: ${drp.layout.content_alignment}`);
  doc.text(`Container max width: ${drp.layout.container_max_px}px`);
  doc.text(`Grid: ${drp.layout.grid.columns} columns, ${drp.layout.grid.gutter_px}px gutter`);
  doc.text(`Breakpoints: ${Object.entries(drp.layout.breakpoints).map(([k, v]) => `${k}=${v}px`).join(', ')}`);

  const navRecipe = (drp.components['layout.sidebar'] ?? drp.components['layout.topbar']) as Record<string, unknown> | undefined;
  const footerRecipe = drp.components['layout.page'] as Record<string, unknown> | undefined;
  if (navRecipe || footerRecipe) {
    doc.moveDown(0.5);
    if (navRecipe?.logo_placement) doc.text(`Logo placement: ${String(navRecipe.logo_placement)}`);
    if (navRecipe?.header_style) doc.text(`Header style: ${String(navRecipe.header_style)}`);
    if (footerRecipe?.footer_style) doc.text(`Footer style: ${String(footerRecipe.footer_style)}`);
  }

  if (drp.anti_patterns.length) {
    doc.moveDown(1);
    sectionHeading(doc, 'Anti-patterns to avoid');
    doc.fontSize(9).font('Helvetica').fillColor('#000000');
    for (const p of drp.anti_patterns) doc.text(`• ${p}`);
  }
}

function drawComponentsPage(doc: PDFKit.PDFDocument, drp: DRP) {
  doc.addPage();
  sectionHeading(doc, 'Components');

  const resolve = (ref: string | undefined): string | undefined => {
    if (!ref) return undefined;
    const match = /^([a-z]+)\.(\d+)$/i.exec(ref);
    if (match) {
      const [, role, step] = match;
      return (drp.color.palette as Record<string, { ramp: Record<string, string> } | undefined>)[role]?.ramp[step];
    }
    return drp.color.semantic[ref] ?? ref;
  };

  const entries = Object.entries(drp.components);
  if (entries.length === 0) {
    doc.fontSize(10).fillColor('#666666').text('No component recipes extracted for this reference.');
    return;
  }

  for (const [role, recipe] of entries) {
    const r = recipe as Record<string, unknown>;
    doc.fontSize(10).font('Helvetica-Bold').fillColor('#000000').text(role);
    const bg = resolve(r.bg as string | undefined);
    const y = doc.y;
    if (bg) {
      doc.rect(PAGE_MARGIN, y, 40, 24).fill(bg).stroke('#DDDDDD');
    }
    const textX = bg ? PAGE_MARGIN + 50 : PAGE_MARGIN;
    doc.fontSize(8).font('Helvetica').fillColor('#666666');
    const details = Object.entries(r)
      .filter(([k]) => k !== 'states')
      .map(([k, v]) => `${k}: ${typeof v === 'object' ? JSON.stringify(v) : String(v)}`)
      .join('  ·  ');
    doc.text(details, textX, y + 4, { width: CONTENT_WIDTH - (bg ? 50 : 0) });
    doc.y = Math.max(doc.y, y + 30);
    doc.moveDown(0.5);
  }
}

function drawProvenancePage(doc: PDFKit.PDFDocument, drp: DRP) {
  doc.addPage();
  sectionHeading(doc, 'Provenance');
  const rows: Array<[string, string]> = [
    ['Source', drp.provenance.source],
    ['Origin URL', drp.provenance.origin_url],
    ['Creator credit', drp.provenance.creator_credit],
    ['Extraction method', drp.provenance.extraction_method],
    ['Confidence', drp.provenance.confidence.toFixed(2)],
    ['Captured at', new Date(drp.provenance.captured_at).toLocaleString()],
  ];
  doc.fontSize(10).font('Helvetica');
  for (const [label, value] of rows) {
    doc.font('Helvetica-Bold').fillColor('#000000').text(`${label}:  `, { continued: true });
    doc.font('Helvetica').fillColor('#444444').text(value);
    doc.moveDown(0.2);
  }

  doc.moveDown(1);
  doc.fontSize(8).fillColor('#999999').text(
    drp.provenance.extraction_method === 'vision_inferred'
      ? 'This profile was inferred by an AI vision model from a screenshot — treat exact hex/font values as close estimates rather than guaranteed-exact.'
      : drp.provenance.extraction_method === 'computed_css'
        ? 'This profile was derived from real computed CSS captured directly from the live site — colours, spacing, and radii reflect actual measured values.'
        : 'This profile was derived from Figma design file data.'
  );
}

function addPageFooters(doc: PDFKit.PDFDocument, drp: DRP) {
  const range = doc.bufferedPageRange();
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(range.start + i);
    doc.fontSize(8).fillColor('#AAAAAA').text(
      `${drp.identity.name} — Brand Guidelines`,
      PAGE_MARGIN,
      doc.page.height - 40,
      { width: CONTENT_WIDTH - 40, lineBreak: false }
    );
    doc.text(`${i + 1} / ${range.count}`, PAGE_WIDTH - PAGE_MARGIN - 40, doc.page.height - 40, { width: 40, align: 'right', lineBreak: false });
  }
}

function contrastTextColor(hex: string): string {
  const c = hex.replace('#', '');
  if (c.length < 6) return '#000000';
  const r = parseInt(c.slice(0, 2), 16);
  const g = parseInt(c.slice(2, 4), 16);
  const b = parseInt(c.slice(4, 6), 16);
  const luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
  return luminance > 0.6 ? '#000000' : '#FFFFFF';
}

function remToPx(rem: string): number {
  const n = parseFloat(rem);
  return Number.isNaN(n) ? 16 : n * 16;
}
