import type { DRP } from '../drp/types.js';

export function renderTailwindTheme(drp: DRP): string {
  const lines: string[] = [];
  lines.push(`// Generated by \`stylesync pack ${drp.ref_id}\`. Tailwind v4 @theme block.`);
  lines.push(`// Import this into your global CSS: @import "./.stylesync/tailwind.theme.ts" is not`);
  lines.push(`// valid CSS — copy the block below into an actual .css file's @theme rule, or if`);
  lines.push(`// you're on Tailwind v3, use the exported \`tailwindV3Extend\` object in tailwind.config.`);
  lines.push('');
  lines.push('export const themeBlockCss = `@theme {');
  for (const [role, ramp] of Object.entries(drp.color.palette)) {
    if (!ramp) continue;
    for (const [step, hex] of Object.entries(ramp.ramp)) {
      lines.push(`  --color-${role}-${step}: ${hex};`);
    }
  }
  for (const [name, step] of Object.entries(drp.typography.scale.steps)) {
    lines.push(`  --text-${name}: ${step.size};`);
    lines.push(`  --text-${name}--line-height: ${step.line};`);
  }
  for (const [name, value] of Object.entries(drp.shape.radius)) {
    lines.push(`  --radius-${name}: ${value};`);
  }
  lines.push('}`;');
  lines.push('');
  lines.push('// Tailwind v3 fallback: spread into theme.extend in tailwind.config.{js,ts}');
  lines.push('export const tailwindV3Extend = {');
  lines.push('  colors: {');
  for (const [role, ramp] of Object.entries(drp.color.palette)) {
    if (!ramp) continue;
    lines.push(`    ${role}: ${JSON.stringify(ramp.ramp)},`);
  }
  lines.push('  },');
  lines.push('  borderRadius: ' + JSON.stringify(drp.shape.radius) + ',');
  lines.push('  fontSize: {');
  for (const [name, step] of Object.entries(drp.typography.scale.steps)) {
    lines.push(`    ${name}: ['${step.size}', { lineHeight: '${step.line}', letterSpacing: '${step.tracking}', fontWeight: '${step.weight}' }],`);
  }
  lines.push('  },');
  lines.push('};');
  return lines.join('\n') + '\n';
}
