import type { DRP } from '../drp/types.js';

export function renderTokensCss(drp: DRP): string {
  const lines: string[] = [];
  lines.push(`/* Generated by \`stylesync pack ${drp.ref_id}\` — do not hand-edit, re-run pack instead. */`);
  lines.push(`:root {`);

  for (const [role, ramp] of Object.entries(drp.color.palette)) {
    if (!ramp) continue;
    for (const [step, hex] of Object.entries(ramp.ramp)) {
      lines.push(`  --color-${role}-${step}: ${hex};`);
    }
  }
  for (const [key, value] of Object.entries(drp.color.semantic)) {
    const varName = key.replace('.', '-');
    lines.push(`  --${varName}: ${resolveSemanticRef(value, drp)};`);
  }

  lines.push(`  --font-display: ${drp.typography.families.display.stack};`);
  lines.push(`  --font-body: ${drp.typography.families.body.stack};`);
  lines.push(`  --font-mono: ${drp.typography.families.mono.stack};`);
  for (const [name, step] of Object.entries(drp.typography.scale.steps)) {
    lines.push(`  --text-${name}: ${step.size};`);
    lines.push(`  --text-${name}-line: ${step.line};`);
    lines.push(`  --text-${name}-tracking: ${step.tracking};`);
    lines.push(`  --text-${name}-weight: ${step.weight};`);
  }

  lines.push(`  --space-unit: ${drp.space.unit_px}px;`);
  drp.space.scale.forEach((stepPx, i) => {
    lines.push(`  --space-${i}: ${stepPx}px;`);
  });

  for (const [name, value] of Object.entries(drp.shape.radius)) {
    lines.push(`  --radius-${name}: ${value};`);
  }
  for (const [name, value] of Object.entries(drp.shape.border_widths)) {
    lines.push(`  --border-${name}: ${value};`);
  }
  for (const [level, value] of Object.entries(drp.elevation.levels)) {
    lines.push(`  --elevation-${level}: ${value};`);
  }

  lines.push(`  --motion-fast: ${drp.motion.durations.fast}ms;`);
  lines.push(`  --motion-base: ${drp.motion.durations.base}ms;`);
  lines.push(`  --motion-slow: ${drp.motion.durations.slow}ms;`);
  for (const [name, value] of Object.entries(drp.motion.easings)) {
    lines.push(`  --ease-${name}: ${value};`);
  }

  lines.push(`}`);
  lines.push('');
  lines.push(`@media (prefers-reduced-motion: reduce) {`);
  lines.push(`  :root { --motion-fast: 0ms; --motion-base: 0ms; --motion-slow: 0ms; }`);
  lines.push(`}`);

  return lines.join('\n') + '\n';
}

function resolveSemanticRef(value: string, drp: DRP): string {
  const match = /^([a-z]+)\.(\d+)$/i.exec(value);
  if (!match) return value;
  const [, role, step] = match;
  const ramp = (drp.color.palette as Record<string, { ramp: Record<string, string> } | undefined>)[role];
  return ramp?.ramp[step] ?? `var(--color-${role}-${step})`;
}
